/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import dao.ProdutosDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Produtos;
import model.Utilities;


/**
 *
 * @author Mateus
 */
public class ProdutoView extends javax.swing.JFrame {

    public void listarTabela() throws SQLException
    {
        ProdutosDao dao = new ProdutosDao();
        List<Produtos> lista = dao.listarProduto();
        DefaultTableModel dados = (DefaultTableModel) jTableProdutos.getModel();
        dados.setNumRows(0);
        
        for(Produtos p : lista)
        {
            try
            {
                dados.addRow(new Object[]
                        {
                            p.getCod(),
                            p.getNome(),
                            p.getPrecoCusto(),
                            p.getPrecoVenda(),
                            p.getIcms(),
                            p.getLucro(),
                            p.getEstoque(),
                            p.getNcm(),
                            p.getUnMedida(),
                            p.getMarca(),
                            p.getModelo(),
                            p.getOrigem(),
                            p.getCodBarras(),
                            p.getSituacao(),
                            p.getCategoria(),
                            p.getInfoAdicionais()
                         }

                        );
            } catch(Exception e)
                {
                    e.printStackTrace();
                }
        }// Fim do bloco de repetição for
        
    }// Fim do método listarTabela
    /**
     * Creates new form ProdutoView
     */
    public ProdutoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitle = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jTabbedTabela = new javax.swing.JTabbedPane();
        jPanelPainelCadastro = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPrecoVenda = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextCategoria = new javax.swing.JTextPane();
        jLabelCategoria = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextSituacao = new javax.swing.JTextPane();
        jLabelInfoAdicionais = new javax.swing.JLabel();
        jLabelLucro = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextOrigem = new javax.swing.JTextPane();
        jLabelSituacao = new javax.swing.JLabel();
        jLabelPrecoCusto = new javax.swing.JLabel();
        jLabelIcms = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextMarca = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextEstoque = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextIcms = new javax.swing.JTextPane();
        jLabelPrecoVenda = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextNome = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextModelo = new javax.swing.JTextPane();
        jLabelUnMedida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextInfoAdicionais = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextCodBarras = new javax.swing.JTextPane();
        jLabelModelo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPrecoCusto = new javax.swing.JTextPane();
        jLabelCodBarras = new javax.swing.JLabel();
        jLabelCod = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextNcm = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextLucro = new javax.swing.JTextPane();
        jLabelEstoque = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextUnMedida = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextCod = new javax.swing.JTextPane();
        jLabelNcm = new javax.swing.JLabel();
        jLabelOrigem = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTitle.setBackground(new java.awt.Color(204, 204, 204));

        jLabelTitle.setBackground(new java.awt.Color(204, 204, 204));
        jLabelTitle.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitle.setText("Cadastro de Produtos");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jButtonNovo.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNovo.setText("NOVO");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("EDITAR");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("PESQUISAR");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jTextPrecoVenda.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane4.setViewportView(jTextPrecoVenda);

        jTextCategoria.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane14.setViewportView(jTextCategoria);

        jLabelCategoria.setText("Categoria");

        jTextSituacao.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane15.setViewportView(jTextSituacao);

        jLabelInfoAdicionais.setText("Informações Adicionais");

        jLabelLucro.setText("Lucro");

        jTextOrigem.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane8.setViewportView(jTextOrigem);

        jLabelSituacao.setText("Situação");

        jLabelPrecoCusto.setText("Preço de Custo");

        jLabelIcms.setText("ICMS");

        jTextMarca.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane11.setViewportView(jTextMarca);

        jTextEstoque.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane7.setViewportView(jTextEstoque);

        jTextIcms.setEditable(false);
        jTextIcms.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane5.setViewportView(jTextIcms);

        jLabelPrecoVenda.setText("Preço de Venda");

        jTextNome.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(jTextNome);

        jTextModelo.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane12.setViewportView(jTextModelo);

        jLabelUnMedida.setText("Un Medida");

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("ATENÇÃO: OS CAMPOS COD, ICMS E LUCRO NÃO SÃO EDITÁVEIS.");

        jLabelMarca.setText("Marca");

        jTextInfoAdicionais.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane16.setViewportView(jTextInfoAdicionais);

        jTextCodBarras.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane13.setViewportView(jTextCodBarras);

        jLabelModelo.setText("Modelo");

        jTextPrecoCusto.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(jTextPrecoCusto);

        jLabelCodBarras.setText("Código de Barras");

        jLabelCod.setText("Cod");

        jTextNcm.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane9.setViewportView(jTextNcm);

        jTextLucro.setEditable(false);
        jTextLucro.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane6.setViewportView(jTextLucro);

        jLabelEstoque.setText("Estoque");

        jLabelNome.setText("Nome");

        jTextUnMedida.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane10.setViewportView(jTextUnMedida);

        jTextCod.setEditable(false);
        jTextCod.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTextCod);

        jLabelNcm.setText("NCM");

        jLabelOrigem.setText("Origem");

        javax.swing.GroupLayout jPanelPainelCadastroLayout = new javax.swing.GroupLayout(jPanelPainelCadastro);
        jPanelPainelCadastro.setLayout(jPanelPainelCadastroLayout);
        jPanelPainelCadastroLayout.setHorizontalGroup(
            jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPainelCadastroLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInfoAdicionais)
                    .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane16)
                            .addGroup(jPanelPainelCadastroLayout.createSequentialGroup()
                                .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCod))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNome)
                                    .addComponent(jScrollPane2)))
                            .addGroup(jPanelPainelCadastroLayout.createSequentialGroup()
                                .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPrecoCusto))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPrecoVenda))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelIcms))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelLucro))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEstoque)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelPainelCadastroLayout.createSequentialGroup()
                                .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelPainelCadastroLayout.createSequentialGroup()
                                            .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPainelCadastroLayout.createSequentialGroup()
                                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18))
                                                .addGroup(jPanelPainelCadastroLayout.createSequentialGroup()
                                                    .addComponent(jLabelNcm)
                                                    .addGap(110, 110, 110)))
                                            .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelUnMedida)
                                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabelCodBarras))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelPainelCadastroLayout.createSequentialGroup()
                                        .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelMarca))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelModelo))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelOrigem)))
                                    .addGroup(jPanelPainelCadastroLayout.createSequentialGroup()
                                        .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelSituacao))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCategoria)
                                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanelPainelCadastroLayout.setVerticalGroup(
            jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPainelCadastroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCod)
                    .addComponent(jLabelNome))
                .addGap(5, 5, 5)
                .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPainelCadastroLayout.createSequentialGroup()
                        .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLucro)
                            .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelPrecoCusto)
                                .addComponent(jLabelPrecoVenda))
                            .addComponent(jLabelEstoque))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNcm)
                            .addComponent(jLabelUnMedida)
                            .addComponent(jLabelMarca)
                            .addComponent(jLabelModelo)
                            .addComponent(jLabelOrigem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelIcms))
                .addGap(18, 18, 18)
                .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPainelCadastroLayout.createSequentialGroup()
                        .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPainelCadastroLayout.createSequentialGroup()
                                .addComponent(jLabelCodBarras)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPainelCadastroLayout.createSequentialGroup()
                                .addComponent(jLabelCategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelPainelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addComponent(jLabelInfoAdicionais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelSituacao))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedTabela.addTab("Produto", jPanelPainelCadastro);

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "Nome", "P Custo", "P Venda", "ICMS", "Lucro", "Estoque", "NCM", "Un Medida", "Marca", "Modelo", "Origem", "Cod Barras", "Situação", "Categoria", "Info Adicionais"
            }
        ));
        jTableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosMouseClicked(evt);
            }
        });
        jScrollPane18.setViewportView(jTableProdutos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        jTabbedTabela.addTab("Tabela de Produtos", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane17.setViewportView(jTable1);

        jTabbedTabela.addTab("tab3", jScrollPane17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButtonNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalvar)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditar)
                .addGap(18, 18, 18)
                .addComponent(jButtonExcluir)
                .addGap(18, 18, 18)
                .addComponent(jButtonPesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedTabela)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedTabela))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
       new Utilities().cleanScreen(jPanelPainelCadastro);
       new Utilities().limpa(jPanelPainelCadastro);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        Produtos obj = new Produtos();

        obj.setNome(jTextNome.getText());
        obj.setPrecoCusto(Double.parseDouble(jTextPrecoCusto.getText()));
        obj.setPrecoVenda(Double.parseDouble(jTextPrecoVenda.getText()));
        obj.setEstoque(Integer.parseInt(jTextEstoque.getText()));
        obj.setNcm(Integer.parseInt(jTextNcm.getText()));
        obj.setUnMedida(jTextUnMedida.getText());
        obj.setMarca(jTextMarca.getText());
        obj.setModelo(jTextModelo.getText());
        obj.setOrigem(jTextOrigem.getText());
        obj.setCodBarras(Integer.parseInt(jTextCodBarras.getText()));
        obj.setSituacao(jTextSituacao.getText());
        obj.setCategoria(jTextCategoria.getText());
        obj.setInfoAdicionais(jTextInfoAdicionais.getText());

        ProdutosDao dao = new ProdutosDao();
        dao.cadProduto(obj);

        new Utilities().cleanScreen(jPanelPainelCadastro);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

        Produtos obj = new Produtos();

        obj.setNome(jTextNome.getText());
        obj.setPrecoCusto(Double.parseDouble(jTextPrecoCusto.getText()));
        obj.setPrecoVenda(Double.parseDouble(jTextPrecoVenda.getText()));
        obj.setEstoque(Integer.parseInt(jTextEstoque.getText()));
        obj.setNcm(Integer.parseInt(jTextNcm.getText()));
        obj.setUnMedida(jTextUnMedida.getText());
        obj.setMarca(jTextMarca.getText());
        obj.setModelo(jTextModelo.getText());
        obj.setOrigem(jTextOrigem.getText());
        obj.setCodBarras(Integer.parseInt(jTextCodBarras.getText()));
        obj.setSituacao(jTextSituacao.getText());
        obj.setCategoria(jTextCategoria.getText());
        obj.setInfoAdicionais(jTextInfoAdicionais.getText());

        ProdutosDao dao = new ProdutosDao();
        dao.alterarProduto(obj);

        new Utilities().cleanScreen(jPanelPainelCadastro);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        Produtos obj = new Produtos();

        obj.setCod(Integer.parseInt(jTextCod.getText()));

        ProdutosDao dao = new ProdutosDao();

        dao.excluirProduto(obj);

        new Utilities().cleanScreen(jPanelPainelCadastro);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

       private void formWindowActivated(java.awt.event.WindowEvent evt) throws SQLException {                                     
        listarTabela();
    }
        
    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        
        String nome = "%" + jTextNome.getText() + "%";
        
        ProdutosDao dao = new ProdutosDao();
        List<Produtos> lista = dao.buscaCad(nome);
        
        DefaultTableModel dados = (DefaultTableModel) jTableProdutos.getModel();
        dados.setNumRows(0);
        
        for (Produtos p : lista)
        {
            dados.addRow(new Object[]
            {
                p.getCod(),
                            p.getNome(),
                            p.getPrecoCusto(),
                            p.getPrecoVenda(),
                            p.getIcms(),
                            p.getLucro(),
                            p.getEstoque(),
                            p.getNcm(),
                            p.getUnMedida(),
                            p.getMarca(),
                            p.getModelo(),
                            p.getOrigem(),
                            p.getCodBarras(),
                            p.getSituacao(),
                            p.getCategoria(),
                            p.getInfoAdicionais()
            }
            );
        }// Fim do bloco de repetição for
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosMouseClicked
        
        jTabbedTabela.setSelectedIndex(0);
        
        jTextCod.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 0).toString());
        jTextNome.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 1).toString());
        jTextPrecoCusto.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 2).toString());
        jTextPrecoVenda.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 3).toString());
        jTextIcms.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 4).toString());
        jTextLucro.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 5).toString());
        jTextEstoque.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 6).toString());
        jTextNcm.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 7).toString());
        jTextUnMedida.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 8).toString());
        jTextMarca.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 9).toString());
        jTextModelo.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 10).toString());
        jTextOrigem.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 11).toString());
        jTextCodBarras.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 12).toString());
        jTextSituacao.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 13).toString());
        jTextCategoria.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 14).toString());
        jTextInfoAdicionais.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 15).toString());
    }//GEN-LAST:event_jTableProdutosMouseClicked


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelCodBarras;
    private javax.swing.JLabel jLabelEstoque;
    private javax.swing.JLabel jLabelIcms;
    private javax.swing.JLabel jLabelInfoAdicionais;
    private javax.swing.JLabel jLabelLucro;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelNcm;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelOrigem;
    private javax.swing.JLabel jLabelPrecoCusto;
    private javax.swing.JLabel jLabelPrecoVenda;
    private javax.swing.JLabel jLabelSituacao;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelUnMedida;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPainelCadastro;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedTabela;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextPane jTextCategoria;
    private javax.swing.JTextPane jTextCod;
    private javax.swing.JTextPane jTextCodBarras;
    private javax.swing.JTextPane jTextEstoque;
    private javax.swing.JTextPane jTextIcms;
    private javax.swing.JTextPane jTextInfoAdicionais;
    private javax.swing.JTextPane jTextLucro;
    private javax.swing.JTextPane jTextMarca;
    private javax.swing.JTextPane jTextModelo;
    private javax.swing.JTextPane jTextNcm;
    private javax.swing.JTextPane jTextNome;
    private javax.swing.JTextPane jTextOrigem;
    private javax.swing.JTextPane jTextPrecoCusto;
    private javax.swing.JTextPane jTextPrecoVenda;
    private javax.swing.JTextPane jTextSituacao;
    private javax.swing.JTextPane jTextUnMedida;
    // End of variables declaration//GEN-END:variables
}
